### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by Owaran** [hopollo/Wakfarm#9]
I have problems with missing files msvcr100d.dll,

PS.: How to active the bot? Just open?

**Comment by hopollo** [comment]
Hi,
This issue is not about the script, have you read and tried the "important" section of the main page ? 

In order to compile this program you may have to download :
Microsoft Visual C++ 2010 SP1 Redistributable Package x86 // x64

And to activate it, you have to download AutoIt and run the script. I maybe gonna release some compiled version later but need more feedbacks first.
